### ISSUE TITLE
Pointshop be BROKE

### ISSUE THREAD

**Issue by riley805** [riley805/BTG_IssueTracker#30] opened 2019-06-12 23:12 UTC
This issue was created in-game by Patrick btg.wtf (76561198136142222)

The pointshop broke. No passes player models or weapons. Ima cri pls fix. If it was intentional than i didnt know rip

**Comment by LunavisM** [comment] 2019-06-12 23:57
dupe of #29

**Closed by LunavisM** 2019-06-12 23:57 UTC
