### ISSUE TITLE
In-Game Suggestion - 76561198018754725

### ISSUE THREAD

**Issue by riley805** [riley805/BTG_IssueTracker#5] opened 2019-05-20 19:34 UTC
ISSUE SUBMITTED ON BEHALF OF: Adamjack [btg.wtf] (76561198018754725)

the web slinger causes whoever uses it's player model to only face north for the remainder of the map.

**Comment by sunshoes** [comment] 2019-05-22 23:57
Duplicate of #3

**Closed by sunshoes** 2019-05-22 23:57 UTC
Labels: duplicate
